# Generated by Django 5.2.6 on 2025-10-12 06:48

import datetime
import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_add_user_to_transaction_history'),
        ('store', '0062_add_return_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sent_to_cashier', 'Sent to Cashier'), ('processed', 'Processed')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('low_stock', 'Low Stock Alert'), ('out_of_stock', 'Out of Stock Alert'), ('expiry_alert', 'Expiry Alert'), ('system_message', 'System Message'), ('procurement_alert', 'Procurement Alert'), ('payment_request', 'Payment Request')], max_length=20),
        ),
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashier_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=8, max_length=50, prefix='CSH:', unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=8, max_length=50, prefix='PRQ:', unique=True)),
                ('payment_type', models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale')], max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='store.cashier')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('dispenser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_request', to='store.receipt')),
                ('wholesale_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.wholesalecustomer')),
                ('wholesale_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_request', to='store.wholesalereceipt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='related_payment_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.paymentrequest'),
        ),
        migrations.CreateModel(
            name='PaymentRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('dosage_form', models.CharField(blank=True, max_length=200, null=True)),
                ('unit', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.paymentrequest')),
                ('retail_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.item')),
                ('wholesale_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.wholesaleitem')),
            ],
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['status', '-created_at'], name='store_payme_status_0391a2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['dispenser', '-created_at'], name='store_payme_dispens_eb24a8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['cashier', '-created_at'], name='store_payme_cashier_2f4d63_idx'),
        ),
    ]
