# Generated by Django 5.2.6 on 2025-10-13 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0063_cart_status_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='cashier',
            field=models.ForeignKey(blank=True, help_text='Cashier who processed this receipt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='store.cashier'),
        ),
        migrations.AddField(
            model_name='wholesalereceipt',
            name='cashier',
            field=models.ForeignKey(blank=True, help_text='Cashier who processed this wholesale receipt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wholesale_receipts', to='store.cashier'),
        ),
    ]
