# Generated by Django 5.1.7 on 2025-10-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0064_add_cashier_to_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashier',
            name='cashier_type',
            field=models.CharField(choices=[('retail', 'Retail Only'), ('wholesale', 'Wholesale Only'), ('both', 'Retail & Wholesale')], default='both', max_length=20),
        ),
    ]
