# Generated by Django 5.1.7 on 2025-10-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0065_add_cashier_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrequest',
            name='approved_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantity approved (may be adjusted).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='requested_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity originally requested.', max_digits=10),
        ),
    ]
