# Generated by Django 5.1.5 on 2025-11-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0066_update_transfer_request_decimal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesalecart',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sent_to_cashier', 'Sent to Cashier'), ('processed', 'Processed')], default='active', max_length=20),
        ),
    ]
