# Generated by Django 5.1.5 on 2025-11-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0067_add_status_to_wholesale_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Primary barcode (UPC/EAN-13/Code-128/QR)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='barcode_type',
            field=models.CharField(blank=True, choices=[('UPC', 'UPC'), ('EAN13', 'EAN-13'), ('CODE128', 'Code-128'), ('QR', 'QR Code'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wholesaleitem',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Primary barcode (UPC/EAN-13/Code-128/QR)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wholesaleitem',
            name='barcode_type',
            field=models.CharField(blank=True, choices=[('UPC', 'UPC'), ('EAN13', 'EAN-13'), ('CODE128', 'Code-128'), ('QR', 'QR Code'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['barcode'], name='store_item_barcode_38064f_idx'),
        ),
        migrations.AddIndex(
            model_name='wholesaleitem',
            index=models.Index(fields=['barcode'], name='store_whole_barcode_d666c9_idx'),
        ),
    ]
