# Generated by Django 5.1.5 on 2025-12-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0068_item_barcode_item_barcode_type_wholesaleitem_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='batch_number',
            field=models.CharField(blank=True, db_index=True, help_text='Batch/lot number from GS1 barcode', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='gtin',
            field=models.CharField(blank=True, db_index=True, help_text='GTIN extracted from GS1 barcode', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, help_text='Serial number from GS1 barcode', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wholesaleitem',
            name='batch_number',
            field=models.CharField(blank=True, db_index=True, help_text='Batch/lot number from GS1 barcode', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wholesaleitem',
            name='gtin',
            field=models.CharField(blank=True, db_index=True, help_text='GTIN extracted from GS1 barcode', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wholesaleitem',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, help_text='Serial number from GS1 barcode', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['gtin'], name='store_item_gtin_2d2b4e_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['batch_number'], name='store_item_batch_n_34aced_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['serial_number'], name='store_item_serial__c32347_idx'),
        ),
        migrations.AddIndex(
            model_name='wholesaleitem',
            index=models.Index(fields=['gtin'], name='store_whole_gtin_f30201_idx'),
        ),
        migrations.AddIndex(
            model_name='wholesaleitem',
            index=models.Index(fields=['batch_number'], name='store_whole_batch_n_b9add2_idx'),
        ),
        migrations.AddIndex(
            model_name='wholesaleitem',
            index=models.Index(fields=['serial_number'], name='store_whole_serial__5e0ce7_idx'),
        ),
    ]
