# Generated by Django 5.1.5 on 2025-12-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0069_add_gs1_barcode_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Barcode transferred from procurement', max_length=200, null=True),
        ),
    ]
