# Generated by Django 5.1.5 on 2025-12-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0070_add_barcode_to_storeitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='low_stock_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
