# Generated by Django 5.1.5 on 2025-12-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0071_alter_item_low_stock_threshold_alter_item_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='buyer_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
