# Generated by Django 5.1.5 on 2026-04-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='contact_email',
        ),
        migrations.AddField(
            model_name='subscription',
            name='contact_mobile',
            field=models.CharField(default='', max_length=20),
        ),
    ]
