# Generated by Django 5.1.5 on 2026-04-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscriptionconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionconfig',
            name='enforcement_enabled',
            field=models.BooleanField(default=True, help_text='When OFF, subscription checks are completely skipped — all users can access the system regardless of subscription status. Turn OFF only for maintenance or testing. Changes take effect immediately.'),
        ),
    ]
