# Generated by Django 5.1.5 on 2025-11-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0007_alter_procurementitem_dosage_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementitem',
            name='barcode',
            field=models.CharField(blank=True, help_text='Barcode for this item', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wholesaleprocurementitem',
            name='barcode',
            field=models.CharField(blank=True, help_text='Barcode for this item', max_length=200, null=True),
        ),
    ]
