# Generated by Django 5.1.5 on 2026-05-23 14:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0008_procurementitem_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='procurement',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Transfer', 'Transfer'), ('Credit', 'Credit'), ('Cheque', 'Cheque')], default='Cash', max_length=20),
        ),
        migrations.AddField(
            model_name='procurement',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='wholesaleprocurement',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='wholesaleprocurement',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Transfer', 'Transfer'), ('Credit', 'Credit'), ('Cheque', 'Cheque')], default='Cash', max_length=20),
        ),
        migrations.AddField(
            model_name='wholesaleprocurement',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
    ]
