# Generated by Django 5.2.6 on 2025-10-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_alter_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Pharmacist', 'Pharmacist'), ('Pharm-Tech', 'Pharm-Tech'), ('Salesperson', 'Salesperson'), ('Cashier', 'Cashier'), ('Wholesale Manager', 'Wholesale Manager'), ('Wholesale Operator', 'Wholesale Operator'), ('Wholesale Salesperson', 'Wholesale Salesperson')], max_length=200, null=True),
        ),
    ]
