# Generated by Django 5.1.5 on 2025-12-07 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_alter_profile_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_password_hash', models.CharField(help_text='Encrypted hash of the old password', max_length=255)),
                ('change_reason', models.TextField(help_text='Reason for the password change')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_changes_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Change History',
                'verbose_name_plural': 'Password Change Histories',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user'], name='userauth_pa_user_id_dc0562_idx'), models.Index(fields=['changed_by'], name='userauth_pa_changed_8efdce_idx'), models.Index(fields=['timestamp'], name='userauth_pa_timesta_de9fbf_idx')],
            },
        ),
    ]
